### ISSUE TITLE
Chnage controls for highlighting

### ISSUE THREAD

**Issue by JosieBarber** [UMM-CSci-3601-F24/it-3-mary-shellys-cool-1918-howard-frankendogs-football-team#5]

**Comment by 0beyer** [comment]
When you ctrl click to bold a cell, it bolds the cell edges all at once, then unbolds all edges, and re bolds all edges one edge at a tme

**Comment by 0beyer** [comment]
it was closed early but yeah it is done now, myb for miscommunication
