### ISSUE TITLE
highlight cells by selecting multiple

### ISSUE THREAD

**Issue by JosieBarber** [UMM-CSci-3601-F24/it-3-mary-shellys-cool-1918-howard-frankendogs-football-team#6]

**Comment by 0beyer** [comment]
I mentioned this in the meeting today, but the drag function does not work how I thought it did, but I have found a workaround, by using mouseleave, we can detect changes simmilar to drag, but this has problems

1. Im not sure how to requre mouseclick to be held for mouseleave to fire
2. when your cursor mooves to fast, it skips over cells
