### ISSUE TITLE
fix edge case blackout bug

### ISSUE THREAD

**Issue by JosieBarber** [UMM-CSci-3601-F24/it-3-mary-shellys-cool-1918-howard-frankendogs-football-team#8]

**Comment by 0beyer** [comment]
found a bug: when you make the cell background white while keeping all edges bold, if you unbold a edge, the cell background goes to black

**Comment by 0beyer** [comment]
> found a bug: when you make the cell background white while keeping all edges bold, if you unbold a edge, the cell background goes to black

fixed this

my work is now DONE
